### ISSUE TITLE
Tjenesten utilgjengelig

### ISSUE THREAD

**Issue by jonarnes** [brreg/regnskapsregister-api#69]
`https://data.brreg.no/regnskapsregisteret/regnskap/swagger-ui/index.html` sier "Application is not available".

Forstår at APIet i utgangspunktet er midlertidig, uten garantier og kan forsvinne uten forvarsel.

Kan noen av de involverte bekrefte aller avkrefte om APIet er tatt ned, evt om det er alternativer tilgjengelig?

**Comment by ChristineHov** [comment]
Hei.

APIet er for øyeblikket nede, men vi jobber med å få det opp igjen, og håper det er på plass igjen innen kort tid.


Med vennlig hilsen

Christine Hovstøl
rådgiver

Brønnøysundregistrene
avdeling registerforvaltning
T: 75 00 79 08
brreg.no<http://www.brreg.no/>



Fra: Jon Arne S. ***@***.***>
Sendt: onsdag 5. juli 2023 09:49
Til: brreg/regnskapsregister-api ***@***.***>
Kopi: Subscribed ***@***.***>
Emne: [brreg/regnskapsregister-api] Tjenesten utilgjengelig (Issue #69)

Det er ikke ofte du mottar e-post fra ***@***.******@***.***>. Finn ut hvorfor dette er viktig.<https://aka.ms/LearnAboutSenderIdentification>
ADVARSEL: Denne e-posten ble sendt fra en ekstern e-postadresse. Ikke trykk på lenker eller åpne vedlegg med mindre du kjenner til avsenderen og vet at innholdet er trygt


https://data.brreg.no/regnskapsregisteret/regnskap/swagger-ui/index.html sier "Application is not available".

Forstår at APIet i utgangspunktet er midlertidig, uten garantier og kan forsvinne uten forvarsel.

Kan noen av de involverte bekrefte aller avkrefte om APIet er tatt ned, evt om det er alternativer tilgjengelig?

-

**Comment by jonarnes** [comment]
Tjenesten er tilgjengelig igjen.
